name: 自动任务

on:
  schedule:
    - cron: "30 21 * * *"
  workflow_dispatch:

env:
  COOKIE: ${{ secrets.COOKIE }}
  WEBHOOK_FEISHU: ${{ secrets.WEBHOOK_FEISHU }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: node index.js
